# Generated by Django 5.2.5 on 2025-08-26 13:48

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Section')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'unique_together': {('name', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('previous_school', models.CharField(blank=True, max_length=100, verbose_name='Previous School')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to=students.models.applicant_document_path, verbose_name='Birth Certificate')),
                ('previous_report_card', models.FileField(blank=True, null=True, upload_to=students.models.applicant_document_path, verbose_name='Previous Report Card')),
                ('class_applying_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class', verbose_name='Class Applying For')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True, verbose_name='Admission Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('admission_date', models.DateField(verbose_name='Admission Date')),
                ('parent_guardian_name', models.CharField(max_length=100, verbose_name='Parent/Guardian Name')),
                ('parent_guardian_phone', models.CharField(max_length=20, verbose_name='Parent/Guardian Phone')),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='Parent/Guardian Email')),
                ('emergency_contact', models.CharField(max_length=20, verbose_name='Emergency Contact')),
                ('blood_group', models.CharField(blank=True, max_length=5, verbose_name='Blood Group')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class', verbose_name='Current Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('record_type', models.CharField(choices=[('merit', 'Merit'), ('demerit', 'Demerit')], max_length=10, verbose_name='Record Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_discipline_records', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Discipline Record',
                'verbose_name_plural': 'Discipline Records',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=students.models.student_document_path, verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
